2018-03-11 11:50:02,083  ERROR Ошибка при валидации Nds4DeductionValidator, userId = 923897, sessionId=850a036a-88fd-4fad-872c-9bb52fa1f78b
System.InvalidCastException: Unable to cast object of type 'ReportsVerification.Web.DataObjects.Xsd.Ndfl6.Файл' to type 'ReportsVerification.Web.DataObjects.Xsd.Nds.Файл'.
   at ReportsVerification.Web.Services.Validation.Nds.Common.CommonNdsDeductionValidator.IsValid(IReadOnlyCollection`1 reports, SessionInfo sessionInfo) in C:\Projects\ReportsVerification\Source\ReportsVerification.Web\Services\Validation\Nds\Common\CommonNdsDeductionValidator.cs:line 49
   at ReportsVerification.Web.Services.Validation.Common.CommonConcreteReportValidator.Validate(IReadOnlyCollection`1 reports, SessionInfo sessionInfo, ValidationType validationType) in C:\Projects\ReportsVerification\Source\ReportsVerification.Web\Services\Validation\Common\CommonConcreteReportValidator.cs:line 26
2018-03-11 11:50:02,128  ERROR Ошибка при валидации Nds4VosmechenieValidator, userId = 923897, sessionId=850a036a-88fd-4fad-872c-9bb52fa1f78b
System.InvalidCastException: Unable to cast object of type 'ReportsVerification.Web.DataObjects.Xsd.Ndfl6.Файл' to type 'ReportsVerification.Web.DataObjects.Xsd.Nds.Файл'.
   at ReportsVerification.Web.Services.Validation.Nds.Common.CommonNdsVosmechenieValidator.IsValid(IReadOnlyCollection`1 reports, SessionInfo sessionInfo) in C:\Projects\ReportsVerification\Source\ReportsVerification.Web\Services\Validation\Nds\Common\CommonNdsVosmechenieValidator.cs:line 40
   at ReportsVerification.Web.Services.Validation.Common.CommonConcreteReportValidator.Validate(IReadOnlyCollection`1 reports, SessionInfo sessionInfo, ValidationType validationType) in C:\Projects\ReportsVerification\Source\ReportsVerification.Web\Services\Validation\Common\CommonConcreteReportValidator.cs:line 26
2018-03-11 11:50:02,166  ERROR Ошибка при валидации Nds1DeductionValidator, userId = 923897, sessionId=850a036a-88fd-4fad-872c-9bb52fa1f78b
System.InvalidCastException: Unable to cast object of type 'ReportsVerification.Web.DataObjects.Xsd.Ndfl6.Файл' to type 'ReportsVerification.Web.DataObjects.Xsd.Nds.Файл'.
   at ReportsVerification.Web.Services.Validation.Nds.Common.CommonNdsDeductionValidator.IsValid(IReadOnlyCollection`1 reports, SessionInfo sessionInfo) in C:\Projects\ReportsVerification\Source\ReportsVerification.Web\Services\Validation\Nds\Common\CommonNdsDeductionValidator.cs:line 49
   at ReportsVerification.Web.Services.Validation.Common.CommonConcreteReportValidator.Validate(IReadOnlyCollection`1 reports, SessionInfo sessionInfo, ValidationType validationType) in C:\Projects\ReportsVerification\Source\ReportsVerification.Web\Services\Validation\Common\CommonConcreteReportValidator.cs:line 26
2018-03-11 11:50:02,209  ERROR Ошибка при валидации Nds1VosmechenieValidator, userId = 923897, sessionId=850a036a-88fd-4fad-872c-9bb52fa1f78b
System.InvalidCastException: Unable to cast object of type 'ReportsVerification.Web.DataObjects.Xsd.Ndfl6.Файл' to type 'ReportsVerification.Web.DataObjects.Xsd.Nds.Файл'.
   at ReportsVerification.Web.Services.Validation.Nds.Common.CommonNdsVosmechenieValidator.IsValid(IReadOnlyCollection`1 reports, SessionInfo sessionInfo) in C:\Projects\ReportsVerification\Source\ReportsVerification.Web\Services\Validation\Nds\Common\CommonNdsVosmechenieValidator.cs:line 40
   at ReportsVerification.Web.Services.Validation.Common.CommonConcreteReportValidator.Validate(IReadOnlyCollection`1 reports, SessionInfo sessionInfo, ValidationType validationType) in C:\Projects\ReportsVerification\Source\ReportsVerification.Web\Services\Validation\Common\CommonConcreteReportValidator.cs:line 26
2018-03-11 11:50:02,243  ERROR Ошибка при валидации Nds2DeductionValidator, userId = 923897, sessionId=850a036a-88fd-4fad-872c-9bb52fa1f78b
System.InvalidCastException: Unable to cast object of type 'ReportsVerification.Web.DataObjects.Xsd.Ndfl6.Файл' to type 'ReportsVerification.Web.DataObjects.Xsd.Nds.Файл'.
   at ReportsVerification.Web.Services.Validation.Nds.Common.CommonNdsDeductionValidator.IsValid(IReadOnlyCollection`1 reports, SessionInfo sessionInfo) in C:\Projects\ReportsVerification\Source\ReportsVerification.Web\Services\Validation\Nds\Common\CommonNdsDeductionValidator.cs:line 49
   at ReportsVerification.Web.Services.Validation.Common.CommonConcreteReportValidator.Validate(IReadOnlyCollection`1 reports, SessionInfo sessionInfo, ValidationType validationType) in C:\Projects\ReportsVerification\Source\ReportsVerification.Web\Services\Validation\Common\CommonConcreteReportValidator.cs:line 26
2018-03-11 11:50:02,282  ERROR Ошибка при валидации Nds2VosmechenieValidator, userId = 923897, sessionId=850a036a-88fd-4fad-872c-9bb52fa1f78b
System.InvalidCastException: Unable to cast object of type 'ReportsVerification.Web.DataObjects.Xsd.Ndfl6.Файл' to type 'ReportsVerification.Web.DataObjects.Xsd.Nds.Файл'.
   at ReportsVerification.Web.Services.Validation.Nds.Common.CommonNdsVosmechenieValidator.IsValid(IReadOnlyCollection`1 reports, SessionInfo sessionInfo) in C:\Projects\ReportsVerification\Source\ReportsVerification.Web\Services\Validation\Nds\Common\CommonNdsVosmechenieValidator.cs:line 40
   at ReportsVerification.Web.Services.Validation.Common.CommonConcreteReportValidator.Validate(IReadOnlyCollection`1 reports, SessionInfo sessionInfo, ValidationType validationType) in C:\Projects\ReportsVerification\Source\ReportsVerification.Web\Services\Validation\Common\CommonConcreteReportValidator.cs:line 26
2018-03-11 11:50:02,316  ERROR Ошибка при валидации Nds3DeductionValidator, userId = 923897, sessionId=850a036a-88fd-4fad-872c-9bb52fa1f78b
System.InvalidCastException: Unable to cast object of type 'ReportsVerification.Web.DataObjects.Xsd.Ndfl6.Файл' to type 'ReportsVerification.Web.DataObjects.Xsd.Nds.Файл'.
   at ReportsVerification.Web.Services.Validation.Nds.Common.CommonNdsDeductionValidator.IsValid(IReadOnlyCollection`1 reports, SessionInfo sessionInfo) in C:\Projects\ReportsVerification\Source\ReportsVerification.Web\Services\Validation\Nds\Common\CommonNdsDeductionValidator.cs:line 49
   at ReportsVerification.Web.Services.Validation.Common.CommonConcreteReportValidator.Validate(IReadOnlyCollection`1 reports, SessionInfo sessionInfo, ValidationType validationType) in C:\Projects\ReportsVerification\Source\ReportsVerification.Web\Services\Validation\Common\CommonConcreteReportValidator.cs:line 26
2018-03-11 11:50:02,354  ERROR Ошибка при валидации Nds3VosmechenieValidator, userId = 923897, sessionId=850a036a-88fd-4fad-872c-9bb52fa1f78b
System.InvalidCastException: Unable to cast object of type 'ReportsVerification.Web.DataObjects.Xsd.Ndfl6.Файл' to type 'ReportsVerification.Web.DataObjects.Xsd.Nds.Файл'.
   at ReportsVerification.Web.Services.Validation.Nds.Common.CommonNdsVosmechenieValidator.IsValid(IReadOnlyCollection`1 reports, SessionInfo sessionInfo) in C:\Projects\ReportsVerification\Source\ReportsVerification.Web\Services\Validation\Nds\Common\CommonNdsVosmechenieValidator.cs:line 40
   at ReportsVerification.Web.Services.Validation.Common.CommonConcreteReportValidator.Validate(IReadOnlyCollection`1 reports, SessionInfo sessionInfo, ValidationType validationType) in C:\Projects\ReportsVerification\Source\ReportsVerification.Web\Services\Validation\Common\CommonConcreteReportValidator.cs:line 26
2018-03-11 11:52:37,369  ERROR Ошибка при валидации Nds4DeductionValidator, userId = 923897, sessionId=850a036a-88fd-4fad-872c-9bb52fa1f78b
System.InvalidCastException: Unable to cast object of type 'ReportsVerification.Web.DataObjects.Xsd.Ndfl6.Файл' to type 'ReportsVerification.Web.DataObjects.Xsd.Nds.Файл'.
   at ReportsVerification.Web.Services.Validation.Nds.Common.CommonNdsDeductionValidator.IsValid(IReadOnlyCollection`1 reports, SessionInfo sessionInfo) in C:\Projects\ReportsVerification\Source\ReportsVerification.Web\Services\Validation\Nds\Common\CommonNdsDeductionValidator.cs:line 49
   at ReportsVerification.Web.Services.Validation.Common.CommonConcreteReportValidator.Validate(IReadOnlyCollection`1 reports, SessionInfo sessionInfo, ValidationType validationType) in C:\Projects\ReportsVerification\Source\ReportsVerification.Web\Services\Validation\Common\CommonConcreteReportValidator.cs:line 26
2018-03-11 11:52:37,415  ERROR Ошибка при валидации Nds4VosmechenieValidator, userId = 923897, sessionId=850a036a-88fd-4fad-872c-9bb52fa1f78b
System.InvalidCastException: Unable to cast object of type 'ReportsVerification.Web.DataObjects.Xsd.Ndfl6.Файл' to type 'ReportsVerification.Web.DataObjects.Xsd.Nds.Файл'.
   at ReportsVerification.Web.Services.Validation.Nds.Common.CommonNdsVosmechenieValidator.IsValid(IReadOnlyCollection`1 reports, SessionInfo sessionInfo) in C:\Projects\ReportsVerification\Source\ReportsVerification.Web\Services\Validation\Nds\Common\CommonNdsVosmechenieValidator.cs:line 40
   at ReportsVerification.Web.Services.Validation.Common.CommonConcreteReportValidator.Validate(IReadOnlyCollection`1 reports, SessionInfo sessionInfo, ValidationType validationType) in C:\Projects\ReportsVerification\Source\ReportsVerification.Web\Services\Validation\Common\CommonConcreteReportValidator.cs:line 26
2018-03-11 11:52:37,455  ERROR Ошибка при валидации Nds1DeductionValidator, userId = 923897, sessionId=850a036a-88fd-4fad-872c-9bb52fa1f78b
System.InvalidCastException: Unable to cast object of type 'ReportsVerification.Web.DataObjects.Xsd.Ndfl6.Файл' to type 'ReportsVerification.Web.DataObjects.Xsd.Nds.Файл'.
   at ReportsVerification.Web.Services.Validation.Nds.Common.CommonNdsDeductionValidator.IsValid(IReadOnlyCollection`1 reports, SessionInfo sessionInfo) in C:\Projects\ReportsVerification\Source\ReportsVerification.Web\Services\Validation\Nds\Common\CommonNdsDeductionValidator.cs:line 49
   at ReportsVerification.Web.Services.Validation.Common.CommonConcreteReportValidator.Validate(IReadOnlyCollection`1 reports, SessionInfo sessionInfo, ValidationType validationType) in C:\Projects\ReportsVerification\Source\ReportsVerification.Web\Services\Validation\Common\CommonConcreteReportValidator.cs:line 26
2018-03-11 11:52:37,491  ERROR Ошибка при валидации Nds1VosmechenieValidator, userId = 923897, sessionId=850a036a-88fd-4fad-872c-9bb52fa1f78b
System.InvalidCastException: Unable to cast object of type 'ReportsVerification.Web.DataObjects.Xsd.Ndfl6.Файл' to type 'ReportsVerification.Web.DataObjects.Xsd.Nds.Файл'.
   at ReportsVerification.Web.Services.Validation.Nds.Common.CommonNdsVosmechenieValidator.IsValid(IReadOnlyCollection`1 reports, SessionInfo sessionInfo) in C:\Projects\ReportsVerification\Source\ReportsVerification.Web\Services\Validation\Nds\Common\CommonNdsVosmechenieValidator.cs:line 40
   at ReportsVerification.Web.Services.Validation.Common.CommonConcreteReportValidator.Validate(IReadOnlyCollection`1 reports, SessionInfo sessionInfo, ValidationType validationType) in C:\Projects\ReportsVerification\Source\ReportsVerification.Web\Services\Validation\Common\CommonConcreteReportValidator.cs:line 26
2018-03-11 11:52:37,528  ERROR Ошибка при валидации Nds2DeductionValidator, userId = 923897, sessionId=850a036a-88fd-4fad-872c-9bb52fa1f78b
System.InvalidCastException: Unable to cast object of type 'ReportsVerification.Web.DataObjects.Xsd.Ndfl6.Файл' to type 'ReportsVerification.Web.DataObjects.Xsd.Nds.Файл'.
   at ReportsVerification.Web.Services.Validation.Nds.Common.CommonNdsDeductionValidator.IsValid(IReadOnlyCollection`1 reports, SessionInfo sessionInfo) in C:\Projects\ReportsVerification\Source\ReportsVerification.Web\Services\Validation\Nds\Common\CommonNdsDeductionValidator.cs:line 49
   at ReportsVerification.Web.Services.Validation.Common.CommonConcreteReportValidator.Validate(IReadOnlyCollection`1 reports, SessionInfo sessionInfo, ValidationType validationType) in C:\Projects\ReportsVerification\Source\ReportsVerification.Web\Services\Validation\Common\CommonConcreteReportValidator.cs:line 26
2018-03-11 11:52:37,566  ERROR Ошибка при валидации Nds2VosmechenieValidator, userId = 923897, sessionId=850a036a-88fd-4fad-872c-9bb52fa1f78b
System.InvalidCastException: Unable to cast object of type 'ReportsVerification.Web.DataObjects.Xsd.Ndfl6.Файл' to type 'ReportsVerification.Web.DataObjects.Xsd.Nds.Файл'.
   at ReportsVerification.Web.Services.Validation.Nds.Common.CommonNdsVosmechenieValidator.IsValid(IReadOnlyCollection`1 reports, SessionInfo sessionInfo) in C:\Projects\ReportsVerification\Source\ReportsVerification.Web\Services\Validation\Nds\Common\CommonNdsVosmechenieValidator.cs:line 40
   at ReportsVerification.Web.Services.Validation.Common.CommonConcreteReportValidator.Validate(IReadOnlyCollection`1 reports, SessionInfo sessionInfo, ValidationType validationType) in C:\Projects\ReportsVerification\Source\ReportsVerification.Web\Services\Validation\Common\CommonConcreteReportValidator.cs:line 26
2018-03-11 11:52:37,601  ERROR Ошибка при валидации Nds3DeductionValidator, userId = 923897, sessionId=850a036a-88fd-4fad-872c-9bb52fa1f78b
System.InvalidCastException: Unable to cast object of type 'ReportsVerification.Web.DataObjects.Xsd.Ndfl6.Файл' to type 'ReportsVerification.Web.DataObjects.Xsd.Nds.Файл'.
   at ReportsVerification.Web.Services.Validation.Nds.Common.CommonNdsDeductionValidator.IsValid(IReadOnlyCollection`1 reports, SessionInfo sessionInfo) in C:\Projects\ReportsVerification\Source\ReportsVerification.Web\Services\Validation\Nds\Common\CommonNdsDeductionValidator.cs:line 49
   at ReportsVerification.Web.Services.Validation.Common.CommonConcreteReportValidator.Validate(IReadOnlyCollection`1 reports, SessionInfo sessionInfo, ValidationType validationType) in C:\Projects\ReportsVerification\Source\ReportsVerification.Web\Services\Validation\Common\CommonConcreteReportValidator.cs:line 26
2018-03-11 11:52:37,637  ERROR Ошибка при валидации Nds3VosmechenieValidator, userId = 923897, sessionId=850a036a-88fd-4fad-872c-9bb52fa1f78b
System.InvalidCastException: Unable to cast object of type 'ReportsVerification.Web.DataObjects.Xsd.Ndfl6.Файл' to type 'ReportsVerification.Web.DataObjects.Xsd.Nds.Файл'.
   at ReportsVerification.Web.Services.Validation.Nds.Common.CommonNdsVosmechenieValidator.IsValid(IReadOnlyCollection`1 reports, SessionInfo sessionInfo) in C:\Projects\ReportsVerification\Source\ReportsVerification.Web\Services\Validation\Nds\Common\CommonNdsVosmechenieValidator.cs:line 40
   at ReportsVerification.Web.Services.Validation.Common.CommonConcreteReportValidator.Validate(IReadOnlyCollection`1 reports, SessionInfo sessionInfo, ValidationType validationType) in C:\Projects\ReportsVerification\Source\ReportsVerification.Web\Services\Validation\Common\CommonConcreteReportValidator.cs:line 26
2018-03-11 12:11:23,365  ERROR Application Error:
System.Data.Entity.Core.EntityException: The underlying provider failed on Open. ---> System.Data.SqlClient.SqlException: A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---> System.ComponentModel.Win32Exception: The network path was not found
   --- End of inner exception stack trace ---
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at System.Data.Entity.Infrastructure.Interception.DbConnectionDispatcher.<Open>b__36(DbConnection t, DbConnectionInterceptionContext c)
   at System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext](TTarget target, Action`2 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)
   at System.Data.Entity.Infrastructure.Interception.DbConnectionDispatcher.Open(DbConnection connection, DbInterceptionContext interceptionContext)
   at System.Data.Entity.Core.EntityClient.EntityConnection.<Open>b__2()
   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.<>c__DisplayClass1.<Execute>b__0()
   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute(Action operation)
   at System.Data.Entity.Core.EntityClient.EntityConnection.Open()
   --- End of inner exception stack trace ---
   at System.Data.Entity.Core.EntityClient.EntityConnection.Open()
   at System.Data.Entity.Core.Objects.ObjectContext.EnsureConnection(Boolean shouldMonitorTransactions)
   at System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<>c__DisplayClass7.<GetResults>b__5()
   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<System.Collections.Generic.IEnumerable<T>.GetEnumerator>b__0()
   at System.Data.Entity.Internal.LazyEnumerator`1.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at System.Data.Entity.Core.Objects.ELinq.ObjectQueryProvider.<GetElementFunction>b__1[TResult](IEnumerable`1 sequence)
   at System.Data.Entity.Core.Objects.ELinq.ObjectQueryProvider.ExecuteSingle[TResult](IEnumerable`1 query, Expression queryRoot)
   at System.Data.Entity.Core.Objects.ELinq.ObjectQueryProvider.System.Linq.IQueryProvider.Execute[TResult](Expression expression)
   at System.Data.Entity.Internal.Linq.DbQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.FirstOrDefault[TSource](IQueryable`1 source, Expression`1 predicate)
   at ReportsVerification.Web.Repositories.SessionRepository.Get(Guid id) in C:\Projects\ReportsVerification\Source\ReportsVerification.Web\Repositories\SessionRepository.cs:line 47
   at ReportsVerification.Web.Utills.Attributes.CheckSessionActionFilterAttribute.OnActionExecuting(HttpActionContext actionContext) in C:\Projects\ReportsVerification\Source\ReportsVerification.Web\Utills\Attributes\CheckSessionActionFilterAttribute.cs:line 31
   at System.Web.Http.Filters.ActionFilterAttribute.OnActionExecutingAsync(HttpActionContext actionContext, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()
2018-03-11 22:54:45,661  ERROR Application Error:
System.Data.Entity.Core.EntityException: The underlying provider failed on Open. ---> System.Data.SqlClient.SqlException: A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---> System.ComponentModel.Win32Exception: The network path was not found
   --- End of inner exception stack trace ---
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at System.Data.Entity.Infrastructure.Interception.DbConnectionDispatcher.<Open>b__36(DbConnection t, DbConnectionInterceptionContext c)
   at System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext](TTarget target, Action`2 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)
   at System.Data.Entity.Infrastructure.Interception.DbConnectionDispatcher.Open(DbConnection connection, DbInterceptionContext interceptionContext)
   at System.Data.Entity.Core.EntityClient.EntityConnection.<Open>b__2()
   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.<>c__DisplayClass1.<Execute>b__0()
   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute(Action operation)
   at System.Data.Entity.Core.EntityClient.EntityConnection.Open()
   --- End of inner exception stack trace ---
   at System.Data.Entity.Core.EntityClient.EntityConnection.Open()
   at System.Data.Entity.Core.Objects.ObjectContext.EnsureConnection(Boolean shouldMonitorTransactions)
   at System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<>c__DisplayClass7.<GetResults>b__5()
   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<System.Collections.Generic.IEnumerable<T>.GetEnumerator>b__0()
   at System.Data.Entity.Internal.LazyEnumerator`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at ReportsVerification.Web.Repositories.ReportsRepository.GetList(Guid sessionId) in C:\Projects\ReportsVerification\Source\ReportsVerification.Web\Repositories\ReportsRepository.cs:line 76
   at ReportsVerification.Web.Controllers.ValidationController.ValidateReports(Guid sessionId, ValidationType type) in C:\Projects\ReportsVerification\Source\ReportsVerification.Web\Controllers\ValidationController.cs:line 47
   at lambda_method(Closure , Object , Object[] )
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()
